name:                hitchhiker-haskell
version:             0.1.0.0
github:              "githubuser/hitchhiker-haskell"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hitchhiker-haskell#readme>

dependencies:
- QuickCheck
- aeson
- base >= 4.7 && < 5
- bytestring
- classy-prelude
- containers
- deepseq
- directory
- filepath
- hashable
- haskey-btree
- mtl
- multimap
- optics
- parsec
- random
- random-shuffle
- repline
- tasty
- tasty-hunit
- tasty-quickcheck
- tasty-th
- text
- unix
- vector
- wai
- wai-app-static
- wai-websockets
- warp
- websockets

ghc-options:
- -Wdefault
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
#- -Wredundant-constraints


library:
  source-dirs: src

executables:
  tag-console:
    main:                Main.hs
    source-dirs:         app/tag-console
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hitchhiker-haskell

  tag-site-demo:
    main:                Main.hs
    source-dirs:         app/tag-site-demo
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hitchhiker-haskell

  sync-imgs:
    main:                Main.hs
    source-dirs:         app/sync-imgs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hitchhiker-haskell
    - http-client
    - http-conduit
    - network-uri

    
tests:
  hitchhiker-haskell-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hitchhiker-haskell


default-extensions:
- ApplicativeDo
- BangPatterns
- BlockArguments
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveDataTypeable
- DeriveFoldable
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DisambiguateRecordFields
- DuplicateRecordFields
- EmptyCase
- EmptyDataDecls
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- ImplicitParams
- LambdaCase
- MagicHash
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- NumericUnderscores
- OverloadedLabels
- OverloadedRecordDot
- OverloadedStrings
- PartialTypeSignatures
- PatternSynonyms
- QuasiQuotes
- Rank2Types
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- UndecidableInstances
- UnicodeSyntax
- ViewPatterns
